// <auto-generated />
using System;
using BTL_WebProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTL_WebProgramming.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20251101155721_Db4")]
    partial class Db4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BTL_WebProgramming.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaCTHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTHD"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HoaDonMaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaVe")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("VeMaVe")
                        .HasColumnType("int");

                    b.HasKey("MaCTHD");

                    b.HasIndex("HoaDonMaHoaDon");

                    b.HasIndex("VeMaVe");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaiTroMaVaiTro")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("VaiTroMaVaiTro");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.SanVanDong", b =>
                {
                    b.Property<int>("MaSVD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSVD"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenSVD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSVD");

                    b.ToTable("SanVanDong", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.TranDau", b =>
                {
                    b.Property<int>("MaTranDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTranDau"));

                    b.Property<string>("DoiChuNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiKhach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaSVD")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThiDau")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SanVanDongMaSVD")
                        .HasColumnType("int");

                    b.HasKey("MaTranDau");

                    b.HasIndex("SanVanDongMaSVD");

                    b.ToTable("TranDau", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"));

                    b.Property<int>("MaTranDau")
                        .HasColumnType("int");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TranDauMaTranDau")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaVe");

                    b.HasIndex("TranDauMaTranDau");

                    b.ToTable("Ve", (string)null);
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("BTL_WebProgramming.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("HoaDonMaHoaDon");

                    b.HasOne("BTL_WebProgramming.Models.Ve", "Ve")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("VeMaVe");

                    b.Navigation("HoaDon");

                    b.Navigation("Ve");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.HoaDon", b =>
                {
                    b.HasOne("BTL_WebProgramming.Models.NguoiDung", "NguoiDung")
                        .WithMany("HoaDon")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.NguoiDung", b =>
                {
                    b.HasOne("BTL_WebProgramming.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDung")
                        .HasForeignKey("VaiTroMaVaiTro");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.TranDau", b =>
                {
                    b.HasOne("BTL_WebProgramming.Models.SanVanDong", "SanVanDong")
                        .WithMany("TranDau")
                        .HasForeignKey("SanVanDongMaSVD");

                    b.Navigation("SanVanDong");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.Ve", b =>
                {
                    b.HasOne("BTL_WebProgramming.Models.TranDau", "TranDau")
                        .WithMany("Ve")
                        .HasForeignKey("TranDauMaTranDau");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.NguoiDung", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.SanVanDong", b =>
                {
                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.TranDau", b =>
                {
                    b.Navigation("Ve");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BTL_WebProgramming.Models.Ve", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });
#pragma warning restore 612, 618
        }
    }
}
